- name: Ensure pip3 is installed
  apt:
    name: python3-pip
    state: present
  become: yes

- name: Install Python libraries for Kafka feeder
  pip:
    name:
      - kafka-python
      - pandas
      - pyarrow
    executable: pip3
