---
- name: Copy zoo.cfg
  template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper_home }}/conf/zoo.cfg"
    owner: "{{ ansible_user }}"
    mode: 0644

- name: Ensure dataDir exists with correct permissions
  file:
    path: /var/lib/zookeeper
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Ensure Zookeeper logs directory has correct permissions
  file:
    path: "{{ zookeeper_home }}/logs"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Start Zookeeper service
  shell: "{{ zookeeper_home }}/bin/zkServer.sh start"
  args:
    executable: /bin/bash

- name: Wait for Zookeeper port to be available
  wait_for:
    port: 2181
    state: started
    timeout: 15
