---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install common system dependencies
  apt:
    name:
      - openjdk-11-jdk
      - python3
      - python3-pip
      - unzip
      - wget
      - curl
      - net-tools
      - git
    state: present

- name: Set JAVA_HOME environment variable
  lineinfile:
    path: /etc/environment
    line: 'JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64'
    create: yes
    state: present

- name: Install useful Python packages (if needed for Spark jobs or provisioning scripts)
  pip:
    name:
      - pyspark
      - kafka-python
      - requests
