- name: Download Kafka
  get_url:
    url: https://downloads.apache.org/kafka/3.9.0/kafka_2.13-3.9.0.tgz
    dest: /opt/kafka.tgz

- name: Extract Kafka
  unarchive:
    src: /opt/kafka.tgz
    dest: /opt/
    remote_src: yes

- name: Symlink Kafka
  file:
    src: /opt/kafka_2.13-3.9.0
    dest: /opt/kafka
    state: link
