---
- name: Install common dependencies (e.g., Java, Python)
  hosts: all
  become: yes
  roles:
    - common

- name: Install Zookeeper on Zookeeper nodes
  hosts: zookeeper
  become: yes
  roles:
    - zookeeper

- name: Install Kafka on Kafka nodes
  hosts: kafka
  become: yes
  roles:
    - kafka

- name: Install Spark on Spark master nodes
  hosts: spark_master
  become: yes
  tasks:
    - include_role:
        name: spark
        tasks_from: main-master

- name: Install Spark on Spark worker nodes
  hosts: spark_workers
  become: yes
  tasks:
    - include_role:
        name: spark
        tasks_from: main-worker

- name: Install dependencies on Kafka feeder node
  hosts: feeder
  become: yes
  roles:
    - feeder
