- name: Run Kafka Feeder
  hosts: feeder
  become: yes
  tasks:
    - name: Upload script
      include_role:
        name: feeder
        tasks_from: upload

    - name: Download data
      include_role:
        name: feeder
        tasks_from: download

    - name: Run script
      include_role:
        name: feeder
        tasks_from: run