- name: Start Zookeeper
  hosts: zookeeper
  become: yes
  tasks:
    - include_role:
        name: zookeeper
        tasks_from: start

- name: Start Kafka
  hosts: kafka
  become: yes
  tasks:
    - include_role:
        name: kafka
        tasks_from: start

- name: Start Spark
  hosts: spark_master:spark_workers
  become: yes
  tasks:
    - include_role:
        name: spark
        tasks_from: start
