- name: Stop ZooKeeper
  hosts: zookeeper
  become: yes
  roles:
    - role: zookeeper
      tasks_from: stop

- name: Stop Kafka Brokers
  hosts: kafka
  become: yes
  roles:
    - role: kafka
      tasks_from: stop
