- name: Stop ZooKeeper
  hosts: zookeeper
  become: yes
  tasks:
    - include_role:
        name: zookeeper
        tasks_from: stop

- name: Stop Kafka Brokers
  hosts: kafka
  become: yes
  tasks:
    - include_role:
        name: kafka
        tasks_from: stop

- name: Shutdown Spark Cluster
  hosts: spark_master:spark_workers
  become: yes
  tasks:
    - include_role:
        name: spark
        tasks_from: stop